"""empty message

Revision ID: 07b09a402414
Revises: c4de76a41e3e
Create Date: 2019-09-13 20:12:04.771727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b09a402414'
down_revision = 'c4de76a41e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('alternative_asking', sa.Text(), nullable=False, comment='Other ways to ask this same question'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'alternative_asking')
    # ### end Alembic commands ###
