"""empty message

Revision ID: 1d36de3e4182
Revises: 7f652890be17
Create Date: 2020-01-10 18:44:05.782766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d36de3e4182'
down_revision = '7f652890be17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alternative_asking', sa.Column('enc_vector', sa.Text(), nullable=True, comment='Encoded vector'))
    op.add_column('questions', sa.Column('enc_vector', sa.Text(), nullable=True, comment='Encoded vector'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'enc_vector')
    op.drop_column('alternative_asking', 'enc_vector')
    # ### end Alembic commands ###
