"""empty message

Revision ID: 1de7acaf1987
Revises: 07b09a402414
Create Date: 2019-10-14 20:34:31.707065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de7acaf1987'
down_revision = '07b09a402414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alternative_asking',
    sa.Column('id', sa.Integer(), nullable=False, comment='Record ID'),
    sa.Column('question', sa.String(length=512), nullable=False, comment='Question'),
    sa.Column('question_id', sa.Integer(), nullable=False, comment='Question ID'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], onupdate='cascade', ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alternative_asking')
    # ### end Alembic commands ###
