"""empty message

Revision ID: 2c00c7e06736
Revises: 1d36de3e4182
Create Date: 2020-03-28 21:40:45.915594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c00c7e06736'
down_revision = '1d36de3e4182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alternative_asking', 'enc_vector')
    op.drop_constraint('questions_ibfk_1', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category_id'], ['id'])
    op.drop_column('questions', 'enc_vector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('enc_vector', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='Encoded vector'))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_ibfk_1', 'questions', 'categories', ['category_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.add_column('alternative_asking', sa.Column('enc_vector', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='Encoded vector'))
    # ### end Alembic commands ###
