"""empty message

Revision ID: 7f652890be17
Revises: 1de7acaf1987
Create Date: 2019-10-14 20:40:52.513139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f652890be17'
down_revision = '1de7acaf1987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'alternative_asking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('alternative_asking', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False, comment='Other ways to ask this same question'))
    # ### end Alembic commands ###
