"""empty message

Revision ID: c4de76a41e3e
Revises: 
Create Date: 2019-09-08 16:46:53.165426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4de76a41e3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False, comment='Category ID'),
    sa.Column('parent', sa.Integer(), nullable=True, comment='Parent category ID, null for root'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Category Name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False, comment='Question ID'),
    sa.Column('category_id', sa.Integer(), nullable=False, comment='Category ID'),
    sa.Column('question', sa.String(length=512), nullable=False, comment='Question'),
    sa.Column('answer', sa.Text(), nullable=True, comment='Answer'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('categories')
    # ### end Alembic commands ###
